version: 0.1
phases:
  #base-directory: src
  install:
    commands:
      #- pip3 install python-coveralls pytest-cov==2.5.0
      #- pip3 install boto3 pytest
      - pip3 uninstall -y pbx_gs_python_utils
      - pip3 install pytest-json

      #- git checkout master


  post_build:
    commands:
      - echo "\n\n****** RUNNING pbx-gs-python-utils/test_QA ********\n\n"
      - cd test_QA && pytest -v --cov=pbx_gs_python_utils --json=report.json
      - cp test_QA/.coverage .
      - coveralls
      #- cd test_QA && pytest --json=report.json utils/test_Files.py
    finally:
      - echo "****** in finally"
      #- pip3 install elasticsearch
      #- cd test_QA && ls -la

      #- cd test_QA && cat PyTest_To_Elk.py
      - cd test_QA && python3 PyTest_To_Elk.py