version: 0.1
phases:
  install:
    commands:
      - python setup.py install

  post_build:
    commands:
      # This tests are going to fail. Mostly all.
      - python setup.py test

#  post_build:
#    commands:
#      - echo "\n\n****** RUNNING pbx-gs-python-utils/test_QA ********\n\n"
#      - cd test_QA && pytest -v --cov=pbx_gs_python_utils --json=report.json
#
#      # the command below requires git installed (which is not on the current docker image)
#      #- cp test_QA/.coverage .
#      #- coveralls
#    finally:
#      - echo "****** in finally"
#      #- pip3 install elasticsearch
#      #- cd test_QA && ls -la
#      - cd test_QA && python3 PyTest_To_Elk.py